// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: message.
// - Entity ID: 102019bb41835f87b408165da8fbc7cd9f9.
// - Entity Version: 102019bb514ed3e7592a5adf116eea9c3f6.
// - Task ID: 6965a6c5cffcfe0afbc61818.
// - Task Root ID: 696565347b69ad7fd26a3748.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for MessageRole
 */
export enum MessageRole {
  Unspecified = 0,
  user = 1,
  assistant = 2,
}



/**
 * Interface for MessageModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface MessageModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  conversation_id: string;
  role: MessageRole;
  content: string;
  image_url?: string | null;
}

/**
 * ORM class for Message entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class MessageORM {
  private static instance: MessageORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019bb41835f87b408165da8fbc7cd9f9';
    this.entityName = 'message';
    this.entityVersion = '102019bb514ed3e7592a5adf116eea9c3f6';
    this.taskId = '6965a6c5cffcfe0afbc61818';
    this.taskRootId = '696565347b69ad7fd26a3748';
  }

  /**
   * Get singleton instance of MessageORM
   */
  public static getInstance(): MessageORM {
    if (!MessageORM.instance) {
      MessageORM.instance = new MessageORM();
    }
    
    return MessageORM.instance;
  }

  /**
   * Get message by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getMessageByIDs(ids: string[]): Promise<MessageModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteMessageByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Message records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllMessage(): Promise<MessageModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Message record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertMessage(data: MessageModel[]): Promise<MessageModel[]> {
    const structured = data.map((item) => CreateData(MessageModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Message records
   */
  async purgeAllMessage(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Message records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listMessage(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[MessageModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get message by Id index
   * This function gets data by index.
   */
  async getMessageById(
    id: string,
  ): Promise<MessageModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) message by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMessageById(
    id: string,
    data: MessageModel
  ): Promise<MessageModel[]> {
    const index = createIndexId(
      id
    );

    const values = MessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by Id index
   */
  async deleteMessageById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get message by DataCreator index
   * This function gets data by index.
   */
  async getMessageByDataCreator(
    data_creator: string,
  ): Promise<MessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) message by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMessageByDataCreator(
    data_creator: string,
    data: MessageModel
  ): Promise<MessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = MessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by DataCreator index
   */
  async deleteMessageByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get message by DataUpdater index
   * This function gets data by index.
   */
  async getMessageByDataUpdater(
    data_updater: string,
  ): Promise<MessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) message by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMessageByDataUpdater(
    data_updater: string,
    data: MessageModel
  ): Promise<MessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = MessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by DataUpdater index
   */
  async deleteMessageByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get message by ConversationId index
   * This function gets data by index.
   */
  async getMessageByConversationId(
    conversation_id: string,
  ): Promise<MessageModel[]> {
    const index = createIndexConversationId(
      conversation_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) message by ConversationId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMessageByConversationId(
    conversation_id: string,
    data: MessageModel
  ): Promise<MessageModel[]> {
    const index = createIndexConversationId(
      conversation_id
    );

    const values = MessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by ConversationId index
   */
  async deleteMessageByConversationId(
    conversation_id: string
  ): Promise<void> {
    const index = createIndexConversationId(
      conversation_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get message by ConversationIdCreateTime index
   * This function gets data by index.
   */
  async getMessageByConversationIdCreateTime(
    conversation_id: string,
    create_time: string,
  ): Promise<MessageModel[]> {
    const index = createIndexConversationIdCreateTime(
      conversation_id,
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) message by ConversationIdCreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setMessageByConversationIdCreateTime(
    conversation_id: string,
    create_time: string,
    data: MessageModel
  ): Promise<MessageModel[]> {
    const index = createIndexConversationIdCreateTime(
      conversation_id,
      create_time
    );

    const values = MessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete message by ConversationIdCreateTime index
   */
  async deleteMessageByConversationIdCreateTime(
    conversation_id: string,
    create_time: string
  ): Promise<void> {
    const index = createIndexConversationIdCreateTime(
      conversation_id,
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to MessageModel data array
   */
  private resultToData(values: Data[]): MessageModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return MessageModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as MessageModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized MessageModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is MessageModel => item !== null);
  }
}

/**
 * Convert MessageModel data to Value array
 */
function MessageModelToValues(data: MessageModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'conversation_id', type: DataType.string, defaultValue: '' },
    { key: 'role', type: DataType.enumeration, defaultValue: 0 },
    { key: 'content', type: DataType.string, defaultValue: '' },
    { key: 'image_url', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof MessageModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to MessageModel data
 */
function MessageModelFromValues(values: Value[]): MessageModel {
  const data: Partial<MessageModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'conversation_id':
        data.conversation_id = ParseValue(value, DataType.string) as string;
        break;
      case 'role':
        data.role = ParseValue(value, DataType.enumeration) as MessageRole;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as MessageModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ConversationId fields
 */
function createIndexConversationId(
  conversation_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, conversation_id, 'conversation_id'),
  ];

  return {
    fields: ['conversation_id'],
    values
  };
}
/**
 * Create index for ConversationIdCreateTime fields
 */
function createIndexConversationIdCreateTime(
  conversation_id: string,
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, conversation_id, 'conversation_id'),
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['conversation_id', 'create_time'],
    values
  };
}

export default MessageORM;